#generated script, Create a file named gitCheckout.groovy under vars folder.
#Here is our Git Checkout shared library code. We have removed all the empty checkout parameters which got generated by default.
#checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: #[[url: 'https://github.com/guneetbh/shared-library-master.git']]])
#############
#def call(Map stageParams) – A simple call function which accepts a Map as an argument. From the pipeline stage, we will pass multiple arguments which get #passed as a map to the shared library.
#stageParams.branch – its the branch parameter which comes from the pipeline stage and we use stageParams to access that variable in the shared library.


def call(Map stageParams) {

    checkout([
        $class: 'GitSCM',
        branches: [[name:  stageParams.branch ]],
        userRemoteConfigs: [[ url: stageParams.url ]]
    ])
  }